### ISSUE TITLE
Password toggle icon doesn't change state 

### ISSUE THREAD

**Issue by deepu2** [aivanovski/kpassnotes#109]
The visibility eye icon doesn't change states when toggled.

![IMG_20221030_115100.jpg](https://user-images.githubusercontent.com/30926681/198865498-fe19ba34-49ee-484b-bc1b-44c9af4a6f78.jpg)

![IMG_20221030_115026.jpg](https://user-images.githubusercontent.com/30926681/198865503-c2d888d0-1727-4293-aabe-daa107991cb3.jpg)

**Comment by aivanovski** [comment]
That will be fixed in next version. I'm going to replace all text fields with outlined design.

**Comment by aivanovski** [comment]
Fixed in #110, will be available in version 0.21.0
