### ISSUE TITLE
file not found nextcloud

### ISSUE THREAD

**Issue by richou672005** [aivanovski/kpassnotes#112]
I type the adress of my nextcloud server correctly , the passwd is ok but it says file not found

**Comment by aivanovski** [comment]
Hi @richou672005, I can't understand what is really happen from your description. Please provide more comprehensive description. For example, you may find out how to create a comprehensive bug report [here](https://www.browserstack.com/guide/how-to-write-a-bug-report)

**Comment by richou672005** [comment]
Sry , i've fou d another way to do what i wanted i used keepass2android but i can remember what happened , i opened the app and choosed the webdav and i put:
Myurl.com/remote.php/dav/username/files/pathtothekeepassfile
I put the correct username and passwd but i got an error "file not found"

**Comment by richou672005** [comment]
I've opened the app choosed webdav and:
Url : https://myurltonextcloud/remote.php/dav/files/usrname/pathtothekeepassfile
Passwd and usrname where correct but i got a file not found in red

**Comment by richou672005** [comment]
But i d'ont need the app anymore , so i hope it will help you

**Comment by aivanovski** [comment]
You provided a path to the file, while the application asks for a URL to the webdav root.

**Comment by richou672005** [comment]
But if i provide the root url it tells me 405 method not supported

**Comment by aivanovski** [comment]
Access to individual files in WebDav will be implemented as a new feature
