### ISSUE TITLE
search can't be used, to many results, virtual * are inserted between all characters of the search string.

### ISSUE THREAD

**Issue by aisbergde** [aivanovski/kpassnotes#191]
The search is the main functionality for me to use KeePass databases. But I get too much results.

example In other keepass client I can search my database for
- softwareone
- eone

and I get only results containing the string "softwareone"

In kpassnotes I get results containing something like the result of

e*o*n*e

This resultset is useless for me. It prevents me to use kpassnotes in a practical way.

The default should be to use the search string as it is, not using each letter of the search string individual. This would be much more intuitive.

**Comment by aivanovski** [comment]
Hi,
Thank you for feedback! By default app uses "Fuzzy" search, the alghorithm is simmilar to [fzf](https://github.com/junegunn/fzf). It can be turned off in "Search screen" -> "Menu button" -> "Sort  View" -> "Search type".
Probably this option could be moved to global settings or at least could be more visible to an eye.

**Comment by aisbergde** [comment]
OK, not so easy to find 😉
search default settings in Application settings would be fine and more intuitive (I was looking in settings) , which could be individually adapted per sort if required.
