### ISSUE TITLE
Access from the item to the containing folder or folder path

### ISSUE THREAD

**Issue by aisbergde** [aivanovski/kpassnotes#192]
I would like to see and access the containing folder of an item.

My usage of keepass databases in desktop clients is not only top down (using the folder tree) but also bottom up:
- I use the search to find any item located in the required folder
- from one found item I access the containing folder
- I can now even navigate to the parent folder

This is possible an all desktop clients, but it's not possible on any android client, which I use:
- keepass2android
- keepassDX

Maybe this could be implemented in kpassnotes?

I imagine this like showing the containing folder or even the whole path and allowing this information for navigation.

**Comment by aivanovski** [comment]
Hey,
That would be a nice feature, sometimes I also need it. Hope I will manage to find some time to implement it.
