### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by julianfairfax** [aivanovski/kpassnotes#206]
KPassNotes isn't a very straightforward or friendly-sounding name. I think it would be nice if the app were renamed. Maybe to something simple like "Passwords", or a bit more complicated, like GNOME's "Secrets".

**Comment by aivanovski** [comment]
Yep, thats true. I've created this app as a sandbox to test new frameworks or programming techniquies. Original idea was to create a note taking app. But suddenly this app became a password manager 😄 Thats's why there is "notes" in the name.

Thanks for ideas, I will try to find more straightforward name! Maybe KPasswords or KSecrets

**Comment by julianfairfax** [comment]
> Thanks for ideas, I will try to find more straightforward name! Maybe KPasswords or KSecrets

Personally I don't really like names with a letter at the front like that. Also, it makes it seem like a KDE app.

**Comment by aivanovski** [comment]
Idea behind "K" in the name, is that it stands for "KeePass". But yes, it's not very straightforward
