### ISSUE TITLE
Issue with cut/paste to an empty group

### ISSUE THREAD

**Issue by rakoo** [aivanovski/kpassnotes#209]
Hey there, thank you for your app !

I just had an issue today with cut-pasting, here's the initial flow:

- Create a group and leave it empty
- In another group (or in the "home page"), cut an entry
- Go to the empty group you just created

Expected: I should be able to paste the entry

Actual: the Paste/Cancel ribbon is not present. I have to create a fake entry, then the ribbon appears, then I can paste my initial entry

**Comment by rakoo** [comment]
Thanks <3

**Comment by aivanovski** [comment]
> Thanks <3

Thank you for reporting this issue.
