### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [aivanovski/kpassnotes#210]
It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by aivanovski** [comment]
From my point of view the risks is relatively low for this project. As I remember there were a lot of concerns regarding what Microsoft was going to do when it acqured GitHub and some of the projects migrated to GitLab. But I don't see any threats for GitHub right now, looks like Microsoft is going to develop it.
